namespace B3RAP_Leecher
{
	// Token: 0x02000009 RID: 9
	[global::Microsoft.VisualBasic.CompilerServices.DesignerGenerated]
	public partial class Main : global::System.Windows.Forms.Form
	{
		// Token: 0x06000049 RID: 73 RVA: 0x0000489C File Offset: 0x00002A9C
		[global::System.Diagnostics.DebuggerNonUserCode]
		protected override void Dispose(bool disposing)
		{
			try
			{
				bool flag = disposing && this.components != null;
				if (flag)
				{
					this.components.Dispose();
				}
			}
			finally
			{
				base.Dispose(disposing);
			}
		}

		// Token: 0x0600004A RID: 74 RVA: 0x000048EC File Offset: 0x00002AEC
		[global::System.Diagnostics.DebuggerStepThrough]
		private void InitializeComponent()
		{
			this.components = new global::System.ComponentModel.Container();
			this.Button1 = new global::System.Windows.Forms.Button();
			this.TextBox1 = new global::System.Windows.Forms.TextBox();
			this.Label1 = new global::System.Windows.Forms.Label();
			this.Label2 = new global::System.Windows.Forms.Label();
			this.Label3 = new global::System.Windows.Forms.Label();
			this.Label4 = new global::System.Windows.Forms.Label();
			this.Label5 = new global::System.Windows.Forms.Label();
			this.TextBox2 = new global::System.Windows.Forms.TextBox();
			this.Label6 = new global::System.Windows.Forms.Label();
			this.TextBox3 = new global::System.Windows.Forms.TextBox();
			this.Button2 = new global::System.Windows.Forms.Button();
			this.Button3 = new global::System.Windows.Forms.Button();
			this.Button4 = new global::System.Windows.Forms.Button();
			this.Button5 = new global::System.Windows.Forms.Button();
			this.Button6 = new global::System.Windows.Forms.Button();
			this.Button7 = new global::System.Windows.Forms.Button();
			this.SaveFileDialog1 = new global::System.Windows.Forms.SaveFileDialog();
			this.Label7 = new global::System.Windows.Forms.Label();
			this.Label8 = new global::System.Windows.Forms.Label();
			this.Label9 = new global::System.Windows.Forms.Label();
			this.Label10 = new global::System.Windows.Forms.Label();
			this.Label11 = new global::System.Windows.Forms.Label();
			this.Label12 = new global::System.Windows.Forms.Label();
			this.OpenFileDialog1 = new global::System.Windows.Forms.OpenFileDialog();
			this.TextBox4 = new global::System.Windows.Forms.TextBox();
			this.TextBox5 = new global::System.Windows.Forms.TextBox();
			this.Button8 = new global::System.Windows.Forms.Button();
			this.Button9 = new global::System.Windows.Forms.Button();
			this.Timer1 = new global::System.Windows.Forms.Timer(this.components);
			base.SuspendLayout();
			this.Button1.BackColor = global::System.Drawing.Color.FromArgb(94, 94, 94);
			this.Button1.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.Button1.FlatAppearance.BorderSize = 0;
			this.Button1.FlatAppearance.MouseDownBackColor = global::System.Drawing.Color.Gray;
			this.Button1.FlatAppearance.MouseOverBackColor = global::System.Drawing.Color.Silver;
			this.Button1.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.Button1.Location = new global::System.Drawing.Point(12, 12);
			this.Button1.Name = "Button1";
			this.Button1.Size = new global::System.Drawing.Size(75, 47);
			this.Button1.TabIndex = 0;
			this.Button1.Text = "Start\r\nLeech";
			this.Button1.UseVisualStyleBackColor = false;
			this.TextBox1.BackColor = global::System.Drawing.Color.FromArgb(94, 94, 94);
			this.TextBox1.BorderStyle = global::System.Windows.Forms.BorderStyle.None;
			this.TextBox1.Font = new global::System.Drawing.Font("Segoe UI", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.TextBox1.ForeColor = global::System.Drawing.Color.WhiteSmoke;
			this.TextBox1.Location = new global::System.Drawing.Point(477, 32);
			this.TextBox1.MaxLength = 999999999;
			this.TextBox1.Multiline = true;
			this.TextBox1.Name = "TextBox1";
			this.TextBox1.Size = new global::System.Drawing.Size(184, 138);
			this.TextBox1.TabIndex = 1;
			this.TextBox1.Text = "@gmail\r\n@hotmail\r\n@yahoo\r\n@yandex";
			this.Label1.AutoSize = true;
			this.Label1.Font = new global::System.Drawing.Font("Segoe UI", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label1.Location = new global::System.Drawing.Point(474, 12);
			this.Label1.Name = "Label1";
			this.Label1.Size = new global::System.Drawing.Size(91, 17);
			this.Label1.TabIndex = 3;
			this.Label1.Text = "Keywords (0) :";
			this.Label2.AutoSize = true;
			this.Label2.Font = new global::System.Drawing.Font("Segoe UI", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label2.Location = new global::System.Drawing.Point(12, 435);
			this.Label2.Name = "Label2";
			this.Label2.Size = new global::System.Drawing.Size(50, 17);
			this.Label2.TabIndex = 5;
			this.Label2.Text = "Status :";
			this.Label3.AutoSize = true;
			this.Label3.Font = new global::System.Drawing.Font("Segoe UI", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label3.Location = new global::System.Drawing.Point(169, 435);
			this.Label3.Name = "Label3";
			this.Label3.Size = new global::System.Drawing.Size(40, 17);
			this.Label3.TabIndex = 6;
			this.Label3.Text = "None";
			this.Label4.AutoSize = true;
			this.Label4.Font = new global::System.Drawing.Font("Segoe UI", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label4.Location = new global::System.Drawing.Point(169, 408);
			this.Label4.Name = "Label4";
			this.Label4.Size = new global::System.Drawing.Size(40, 17);
			this.Label4.TabIndex = 8;
			this.Label4.Text = "None";
			this.Label5.AutoSize = true;
			this.Label5.Font = new global::System.Drawing.Font("Segoe UI", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label5.Location = new global::System.Drawing.Point(12, 408);
			this.Label5.Name = "Label5";
			this.Label5.Size = new global::System.Drawing.Size(151, 17);
			this.Label5.TabIndex = 7;
			this.Label5.Text = "Current Keyword in use :";
			this.TextBox2.BackColor = global::System.Drawing.Color.FromArgb(94, 94, 94);
			this.TextBox2.BorderStyle = global::System.Windows.Forms.BorderStyle.None;
			this.TextBox2.Font = new global::System.Drawing.Font("Segoe UI", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.TextBox2.ForeColor = global::System.Drawing.Color.WhiteSmoke;
			this.TextBox2.Location = new global::System.Drawing.Point(93, 12);
			this.TextBox2.MaxLength = 999999999;
			this.TextBox2.Multiline = true;
			this.TextBox2.Name = "TextBox2";
			this.TextBox2.ReadOnly = true;
			this.TextBox2.ScrollBars = global::System.Windows.Forms.ScrollBars.Both;
			this.TextBox2.Size = new global::System.Drawing.Size(375, 365);
			this.TextBox2.TabIndex = 9;
			this.TextBox2.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Center;
			this.Label6.AutoSize = true;
			this.Label6.Font = new global::System.Drawing.Font("Segoe UI", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label6.Location = new global::System.Drawing.Point(474, 219);
			this.Label6.Name = "Label6";
			this.Label6.Size = new global::System.Drawing.Size(96, 17);
			this.Label6.TabIndex = 14;
			this.Label6.Text = "Paste Sites (0) :";
			this.TextBox3.BackColor = global::System.Drawing.Color.FromArgb(94, 94, 94);
			this.TextBox3.BorderStyle = global::System.Windows.Forms.BorderStyle.None;
			this.TextBox3.Font = new global::System.Drawing.Font("Segoe UI", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.TextBox3.ForeColor = global::System.Drawing.Color.WhiteSmoke;
			this.TextBox3.Location = new global::System.Drawing.Point(477, 239);
			this.TextBox3.Multiline = true;
			this.TextBox3.Name = "TextBox3";
			this.TextBox3.Size = new global::System.Drawing.Size(184, 138);
			this.TextBox3.TabIndex = 13;
			this.TextBox3.Text = "pastebin.com\r\npasteio.com\r\npaste2.org\r\npaste.ee\r\npastr.io\r\nthrowbin.io";
			this.Button2.BackColor = global::System.Drawing.Color.FromArgb(94, 94, 94);
			this.Button2.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.Button2.Enabled = false;
			this.Button2.FlatAppearance.BorderSize = 0;
			this.Button2.FlatAppearance.MouseDownBackColor = global::System.Drawing.Color.Gray;
			this.Button2.FlatAppearance.MouseOverBackColor = global::System.Drawing.Color.Silver;
			this.Button2.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.Button2.Location = new global::System.Drawing.Point(12, 65);
			this.Button2.Name = "Button2";
			this.Button2.Size = new global::System.Drawing.Size(75, 47);
			this.Button2.TabIndex = 15;
			this.Button2.Text = "Stop\r\nLeech";
			this.Button2.UseVisualStyleBackColor = false;
			this.Button3.BackColor = global::System.Drawing.Color.FromArgb(94, 94, 94);
			this.Button3.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.Button3.FlatAppearance.BorderSize = 0;
			this.Button3.FlatAppearance.MouseDownBackColor = global::System.Drawing.Color.Gray;
			this.Button3.FlatAppearance.MouseOverBackColor = global::System.Drawing.Color.Silver;
			this.Button3.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.Button3.Location = new global::System.Drawing.Point(12, 118);
			this.Button3.Name = "Button3";
			this.Button3.Size = new global::System.Drawing.Size(75, 47);
			this.Button3.TabIndex = 16;
			this.Button3.Text = "Search Engines";
			this.Button3.UseVisualStyleBackColor = false;
			this.Button4.BackColor = global::System.Drawing.Color.FromArgb(94, 94, 94);
			this.Button4.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.Button4.FlatAppearance.BorderSize = 0;
			this.Button4.FlatAppearance.MouseDownBackColor = global::System.Drawing.Color.Gray;
			this.Button4.FlatAppearance.MouseOverBackColor = global::System.Drawing.Color.Silver;
			this.Button4.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.Button4.Location = new global::System.Drawing.Point(12, 171);
			this.Button4.Name = "Button4";
			this.Button4.Size = new global::System.Drawing.Size(75, 47);
			this.Button4.TabIndex = 17;
			this.Button4.Text = "Leech Options";
			this.Button4.UseVisualStyleBackColor = false;
			this.Button5.BackColor = global::System.Drawing.Color.FromArgb(94, 94, 94);
			this.Button5.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.Button5.Enabled = false;
			this.Button5.FlatAppearance.BorderSize = 0;
			this.Button5.FlatAppearance.MouseDownBackColor = global::System.Drawing.Color.Gray;
			this.Button5.FlatAppearance.MouseOverBackColor = global::System.Drawing.Color.Silver;
			this.Button5.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.Button5.Location = new global::System.Drawing.Point(12, 224);
			this.Button5.Name = "Button5";
			this.Button5.Size = new global::System.Drawing.Size(75, 47);
			this.Button5.TabIndex = 18;
			this.Button5.Text = "Remove Duplicates";
			this.Button5.UseVisualStyleBackColor = false;
			this.Button6.BackColor = global::System.Drawing.Color.FromArgb(94, 94, 94);
			this.Button6.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.Button6.Enabled = false;
			this.Button6.FlatAppearance.BorderSize = 0;
			this.Button6.FlatAppearance.MouseDownBackColor = global::System.Drawing.Color.Gray;
			this.Button6.FlatAppearance.MouseOverBackColor = global::System.Drawing.Color.Silver;
			this.Button6.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.Button6.Location = new global::System.Drawing.Point(12, 277);
			this.Button6.Name = "Button6";
			this.Button6.Size = new global::System.Drawing.Size(75, 47);
			this.Button6.TabIndex = 19;
			this.Button6.Text = "Save Result";
			this.Button6.UseVisualStyleBackColor = false;
			this.Button7.BackColor = global::System.Drawing.Color.FromArgb(94, 94, 94);
			this.Button7.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.Button7.FlatAppearance.BorderSize = 0;
			this.Button7.FlatAppearance.MouseDownBackColor = global::System.Drawing.Color.Gray;
			this.Button7.FlatAppearance.MouseOverBackColor = global::System.Drawing.Color.Silver;
			this.Button7.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.Button7.Location = new global::System.Drawing.Point(12, 330);
			this.Button7.Name = "Button7";
			this.Button7.Size = new global::System.Drawing.Size(75, 47);
			this.Button7.TabIndex = 20;
			this.Button7.Text = "About";
			this.Button7.UseVisualStyleBackColor = false;
			this.SaveFileDialog1.Filter = "Text files|*.txt";
			this.Label7.AutoSize = true;
			this.Label7.Font = new global::System.Drawing.Font("Segoe UI", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label7.Location = new global::System.Drawing.Point(440, 434);
			this.Label7.Name = "Label7";
			this.Label7.Size = new global::System.Drawing.Size(106, 17);
			this.Label7.TabIndex = 21;
			this.Label7.Text = "Scraping Errors :";
			this.Label8.AutoSize = true;
			this.Label8.Font = new global::System.Drawing.Font("Segoe UI", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label8.Location = new global::System.Drawing.Point(440, 461);
			this.Label8.Name = "Label8";
			this.Label8.Size = new global::System.Drawing.Size(106, 17);
			this.Label8.TabIndex = 22;
			this.Label8.Text = "Program Errors :";
			this.Label9.AutoSize = true;
			this.Label9.Font = new global::System.Drawing.Font("Segoe UI", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label9.ForeColor = global::System.Drawing.Color.Red;
			this.Label9.Location = new global::System.Drawing.Point(552, 434);
			this.Label9.Name = "Label9";
			this.Label9.Size = new global::System.Drawing.Size(15, 17);
			this.Label9.TabIndex = 23;
			this.Label9.Text = "0";
			this.Label10.AutoSize = true;
			this.Label10.Font = new global::System.Drawing.Font("Segoe UI", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label10.ForeColor = global::System.Drawing.Color.Red;
			this.Label10.Location = new global::System.Drawing.Point(552, 461);
			this.Label10.Name = "Label10";
			this.Label10.Size = new global::System.Drawing.Size(15, 17);
			this.Label10.TabIndex = 24;
			this.Label10.Text = "0";
			this.Label11.AutoSize = true;
			this.Label11.Font = new global::System.Drawing.Font("Segoe UI", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label11.Location = new global::System.Drawing.Point(169, 461);
			this.Label11.Name = "Label11";
			this.Label11.Size = new global::System.Drawing.Size(15, 17);
			this.Label11.TabIndex = 26;
			this.Label11.Text = "0";
			this.Label12.AutoSize = true;
			this.Label12.Font = new global::System.Drawing.Font("Segoe UI", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label12.Location = new global::System.Drawing.Point(12, 461);
			this.Label12.Name = "Label12";
			this.Label12.Size = new global::System.Drawing.Size(50, 17);
			this.Label12.TabIndex = 25;
			this.Label12.Text = "Result :";
			this.OpenFileDialog1.Filter = "Text files|*.txt";
			this.OpenFileDialog1.Title = "Select your proxylist :";
			this.TextBox4.BackColor = global::System.Drawing.Color.FromArgb(78, 78, 78);
			this.TextBox4.BorderStyle = global::System.Windows.Forms.BorderStyle.None;
			this.TextBox4.Font = new global::System.Drawing.Font("Segoe UI", 9f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.TextBox4.ForeColor = global::System.Drawing.Color.WhiteSmoke;
			this.TextBox4.Location = new global::System.Drawing.Point(715, 419);
			this.TextBox4.Multiline = true;
			this.TextBox4.Name = "TextBox4";
			this.TextBox4.ReadOnly = true;
			this.TextBox4.ScrollBars = global::System.Windows.Forms.ScrollBars.Both;
			this.TextBox4.Size = new global::System.Drawing.Size(23, 15);
			this.TextBox4.TabIndex = 30;
			this.TextBox5.Location = new global::System.Drawing.Point(738, 78);
			this.TextBox5.Multiline = true;
			this.TextBox5.Name = "TextBox5";
			this.TextBox5.Size = new global::System.Drawing.Size(272, 254);
			this.TextBox5.TabIndex = 31;
			this.Button8.BackColor = global::System.Drawing.Color.FromArgb(94, 94, 94);
			this.Button8.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.Button8.FlatAppearance.BorderSize = 0;
			this.Button8.FlatAppearance.MouseDownBackColor = global::System.Drawing.Color.Gray;
			this.Button8.FlatAppearance.MouseOverBackColor = global::System.Drawing.Color.Silver;
			this.Button8.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.Button8.Location = new global::System.Drawing.Point(477, 176);
			this.Button8.Name = "Button8";
			this.Button8.Size = new global::System.Drawing.Size(184, 40);
			this.Button8.TabIndex = 32;
			this.Button8.Text = "More Options";
			this.Button8.UseVisualStyleBackColor = false;
			this.Button9.BackColor = global::System.Drawing.Color.FromArgb(94, 94, 94);
			this.Button9.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.Button9.FlatAppearance.BorderSize = 0;
			this.Button9.FlatAppearance.MouseDownBackColor = global::System.Drawing.Color.Gray;
			this.Button9.FlatAppearance.MouseOverBackColor = global::System.Drawing.Color.Silver;
			this.Button9.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.Button9.Location = new global::System.Drawing.Point(477, 383);
			this.Button9.Name = "Button9";
			this.Button9.Size = new global::System.Drawing.Size(184, 30);
			this.Button9.TabIndex = 33;
			this.Button9.Text = "Test";
			this.Button9.UseVisualStyleBackColor = false;
			this.Timer1.Interval = 10000;
			base.AutoScaleDimensions = new global::System.Drawing.SizeF(7f, 15f);
			base.AutoScaleMode = global::System.Windows.Forms.AutoScaleMode.Font;
			base.AutoSizeMode = global::System.Windows.Forms.AutoSizeMode.GrowAndShrink;
			this.BackColor = global::System.Drawing.Color.FromArgb(64, 64, 64);
			base.ClientSize = new global::System.Drawing.Size(676, 487);
			base.Controls.Add(this.Button9);
			base.Controls.Add(this.Button8);
			base.Controls.Add(this.TextBox5);
			base.Controls.Add(this.TextBox4);
			base.Controls.Add(this.Label11);
			base.Controls.Add(this.Label12);
			base.Controls.Add(this.Label10);
			base.Controls.Add(this.Label9);
			base.Controls.Add(this.Label8);
			base.Controls.Add(this.Label7);
			base.Controls.Add(this.Button7);
			base.Controls.Add(this.Button6);
			base.Controls.Add(this.Button5);
			base.Controls.Add(this.Button4);
			base.Controls.Add(this.Button3);
			base.Controls.Add(this.Button2);
			base.Controls.Add(this.Label6);
			base.Controls.Add(this.TextBox3);
			base.Controls.Add(this.TextBox2);
			base.Controls.Add(this.Label4);
			base.Controls.Add(this.Label5);
			base.Controls.Add(this.Label3);
			base.Controls.Add(this.Label2);
			base.Controls.Add(this.Label1);
			base.Controls.Add(this.TextBox1);
			base.Controls.Add(this.Button1);
			this.Font = new global::System.Drawing.Font("Segoe UI", 9f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.ForeColor = global::System.Drawing.Color.WhiteSmoke;
			base.FormBorderStyle = global::System.Windows.Forms.FormBorderStyle.FixedDialog;
			base.MaximizeBox = false;
			base.Name = "Main";
			base.ShowIcon = false;
			base.StartPosition = global::System.Windows.Forms.FormStartPosition.CenterScreen;
			base.ResumeLayout(false);
			base.PerformLayout();
		}

		// Token: 0x0400002B RID: 43
		private global::System.ComponentModel.IContainer components;
	}
}
