namespace Joker_Combo_Leecher__v1._0_
{
	// Token: 0x0200000B RID: 11
	[global::Microsoft.VisualBasic.CompilerServices.DesignerGenerated]
	public partial class Form1 : global::System.Windows.Forms.Form
	{
		// Token: 0x06000047 RID: 71 RVA: 0x000066FC File Offset: 0x000048FC
		[global::System.Diagnostics.DebuggerNonUserCode]
		protected override void Dispose(bool disposing)
		{
			try
			{
				bool flag = disposing && this.components != null;
				if (flag)
				{
					this.components.Dispose();
				}
			}
			finally
			{
				base.Dispose(disposing);
			}
		}

		// Token: 0x06000048 RID: 72 RVA: 0x0000674C File Offset: 0x0000494C
		[global::System.Diagnostics.DebuggerStepThrough]
		private void InitializeComponent()
		{
			this.components = new global::System.ComponentModel.Container();
			global::System.ComponentModel.ComponentResourceManager componentResourceManager = new global::System.ComponentModel.ComponentResourceManager(typeof(global::Joker_Combo_Leecher__v1._0_.Form1));
			this.BindingSource1 = new global::System.Windows.Forms.BindingSource(this.components);
			this.VisualStyler1 = new global::SkinSoft.VisualStyler.VisualStyler(this.components);
			this.TabControl1 = new global::System.Windows.Forms.TabControl();
			this.TabPage1 = new global::System.Windows.Forms.TabPage();
			this.GroupBox3 = new global::System.Windows.Forms.GroupBox();
			this.CheckBox4 = new global::System.Windows.Forms.CheckBox();
			this.CheckBox3 = new global::System.Windows.Forms.CheckBox();
			this.CheckBox2 = new global::System.Windows.Forms.CheckBox();
			this.CheckBox1 = new global::System.Windows.Forms.CheckBox();
			this.GroupBox2 = new global::System.Windows.Forms.GroupBox();
			this.RadioButton6 = new global::System.Windows.Forms.RadioButton();
			this.RadioButton5 = new global::System.Windows.Forms.RadioButton();
			this.RadioButton4 = new global::System.Windows.Forms.RadioButton();
			this.RadioButton3 = new global::System.Windows.Forms.RadioButton();
			this.RadioButton2 = new global::System.Windows.Forms.RadioButton();
			this.RadioButton1 = new global::System.Windows.Forms.RadioButton();
			this.GroupBox1 = new global::System.Windows.Forms.GroupBox();
			this.Label11 = new global::System.Windows.Forms.Label();
			this.Label5 = new global::System.Windows.Forms.Label();
			this.HideSolution = new global::System.Windows.Forms.Label();
			this.Label13 = new global::System.Windows.Forms.Label();
			this.Label8 = new global::System.Windows.Forms.Label();
			this.Label3 = new global::System.Windows.Forms.Label();
			this.Button4 = new global::System.Windows.Forms.Button();
			this.TextBox2 = new global::System.Windows.Forms.TextBox();
			this.Button2 = new global::System.Windows.Forms.Button();
			this.Button1 = new global::System.Windows.Forms.Button();
			this.TextBox1 = new global::System.Windows.Forms.TextBox();
			this.TabPage2 = new global::System.Windows.Forms.TabPage();
			this.Button6 = new global::System.Windows.Forms.Button();
			this.GroupBox4 = new global::System.Windows.Forms.GroupBox();
			this.Label19 = new global::System.Windows.Forms.Label();
			this.Label20 = new global::System.Windows.Forms.Label();
			this.Label9 = new global::System.Windows.Forms.Label();
			this.Label10 = new global::System.Windows.Forms.Label();
			this.Label12 = new global::System.Windows.Forms.Label();
			this.Label14 = new global::System.Windows.Forms.Label();
			this.Label15 = new global::System.Windows.Forms.Label();
			this.Label16 = new global::System.Windows.Forms.Label();
			this.Label17 = new global::System.Windows.Forms.Label();
			this.Label18 = new global::System.Windows.Forms.Label();
			this.Button8 = new global::System.Windows.Forms.Button();
			this.Button7 = new global::System.Windows.Forms.Button();
			this.Label7 = new global::System.Windows.Forms.Label();
			this.ComboBox2 = new global::System.Windows.Forms.ComboBox();
			this.Label2 = new global::System.Windows.Forms.Label();
			this.Button5 = new global::System.Windows.Forms.Button();
			this.Button3 = new global::System.Windows.Forms.Button();
			this.ComboBox1 = new global::System.Windows.Forms.ComboBox();
			this.Label1 = new global::System.Windows.Forms.Label();
			this.NumericUpDown1 = new global::System.Windows.Forms.NumericUpDown();
			this.TextBox3 = new global::System.Windows.Forms.TextBox();
			this.Timer1 = new global::System.Windows.Forms.Timer(this.components);
			((global::System.ComponentModel.ISupportInitialize)this.BindingSource1).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.VisualStyler1).BeginInit();
			this.TabControl1.SuspendLayout();
			this.TabPage1.SuspendLayout();
			this.GroupBox3.SuspendLayout();
			this.GroupBox2.SuspendLayout();
			this.GroupBox1.SuspendLayout();
			this.TabPage2.SuspendLayout();
			this.GroupBox4.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.NumericUpDown1).BeginInit();
			base.SuspendLayout();
			this.VisualStyler1.HostForm = this;
			this.VisualStyler1.License = (global::SkinSoft.VisualStyler.Licensing.VisualStylerLicense)componentResourceManager.GetObject("VisualStyler1.License");
			this.VisualStyler1.LoadVisualStyle(null, "ConcaveD (Normal).vssf");
			this.TabControl1.Controls.Add(this.TabPage1);
			this.TabControl1.Controls.Add(this.TabPage2);
			this.TabControl1.Location = new global::System.Drawing.Point(4, 5);
			this.TabControl1.Name = "TabControl1";
			this.TabControl1.SelectedIndex = 0;
			this.TabControl1.Size = new global::System.Drawing.Size(513, 385);
			this.TabControl1.TabIndex = 25;
			this.TabPage1.Controls.Add(this.GroupBox3);
			this.TabPage1.Controls.Add(this.GroupBox2);
			this.TabPage1.Controls.Add(this.GroupBox1);
			this.TabPage1.Controls.Add(this.Button4);
			this.TabPage1.Controls.Add(this.TextBox2);
			this.TabPage1.Controls.Add(this.Button2);
			this.TabPage1.Controls.Add(this.Button1);
			this.TabPage1.Controls.Add(this.TextBox1);
			this.TabPage1.Location = new global::System.Drawing.Point(4, 22);
			this.TabPage1.Name = "TabPage1";
			this.TabPage1.Padding = new global::System.Windows.Forms.Padding(3);
			this.TabPage1.Size = new global::System.Drawing.Size(505, 359);
			this.TabPage1.TabIndex = 0;
			this.TabPage1.Text = "Url's Grabber";
			this.TabPage1.UseVisualStyleBackColor = true;
			this.GroupBox3.Controls.Add(this.CheckBox4);
			this.GroupBox3.Controls.Add(this.CheckBox3);
			this.GroupBox3.Controls.Add(this.CheckBox2);
			this.GroupBox3.Controls.Add(this.CheckBox1);
			this.GroupBox3.Location = new global::System.Drawing.Point(5, 112);
			this.GroupBox3.Name = "GroupBox3";
			this.GroupBox3.Size = new global::System.Drawing.Size(495, 48);
			this.GroupBox3.TabIndex = 33;
			this.GroupBox3.TabStop = false;
			this.CheckBox4.AutoSize = true;
			this.CheckBox4.Checked = true;
			this.CheckBox4.CheckState = global::System.Windows.Forms.CheckState.Checked;
			this.CheckBox4.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 238);
			this.CheckBox4.Location = new global::System.Drawing.Point(399, 14);
			this.CheckBox4.Name = "CheckBox4";
			this.CheckBox4.Size = new global::System.Drawing.Size(86, 24);
			this.CheckBox4.TabIndex = 7;
			this.CheckBox4.Text = "Anonfile";
			this.CheckBox4.UseVisualStyleBackColor = true;
			this.CheckBox3.AutoSize = true;
			this.CheckBox3.Checked = true;
			this.CheckBox3.CheckState = global::System.Windows.Forms.CheckState.Checked;
			this.CheckBox3.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 238);
			this.CheckBox3.Location = new global::System.Drawing.Point(274, 14);
			this.CheckBox3.Name = "CheckBox3";
			this.CheckBox3.Size = new global::System.Drawing.Size(85, 24);
			this.CheckBox3.TabIndex = 6;
			this.CheckBox3.Text = "Forum's";
			this.CheckBox3.UseVisualStyleBackColor = true;
			this.CheckBox2.AutoSize = true;
			this.CheckBox2.Checked = true;
			this.CheckBox2.CheckState = global::System.Windows.Forms.CheckState.Checked;
			this.CheckBox2.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 238);
			this.CheckBox2.Location = new global::System.Drawing.Point(145, 14);
			this.CheckBox2.Name = "CheckBox2";
			this.CheckBox2.Size = new global::System.Drawing.Size(90, 24);
			this.CheckBox2.TabIndex = 5;
			this.CheckBox2.Text = "Pastebin";
			this.CheckBox2.UseVisualStyleBackColor = true;
			this.CheckBox1.AutoSize = true;
			this.CheckBox1.Checked = true;
			this.CheckBox1.CheckState = global::System.Windows.Forms.CheckState.Checked;
			this.CheckBox1.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 238);
			this.CheckBox1.Location = new global::System.Drawing.Point(26, 14);
			this.CheckBox1.Name = "CheckBox1";
			this.CheckBox1.Size = new global::System.Drawing.Size(80, 24);
			this.CheckBox1.TabIndex = 4;
			this.CheckBox1.Text = "Google";
			this.CheckBox1.UseVisualStyleBackColor = true;
			this.GroupBox2.Controls.Add(this.RadioButton6);
			this.GroupBox2.Controls.Add(this.RadioButton5);
			this.GroupBox2.Controls.Add(this.RadioButton4);
			this.GroupBox2.Controls.Add(this.RadioButton3);
			this.GroupBox2.Controls.Add(this.RadioButton2);
			this.GroupBox2.Controls.Add(this.RadioButton1);
			this.GroupBox2.Location = new global::System.Drawing.Point(323, 164);
			this.GroupBox2.Name = "GroupBox2";
			this.GroupBox2.Size = new global::System.Drawing.Size(177, 191);
			this.GroupBox2.TabIndex = 32;
			this.GroupBox2.TabStop = false;
			this.GroupBox2.Text = "Search Time";
			this.RadioButton6.AutoSize = true;
			this.RadioButton6.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 238);
			this.RadioButton6.Location = new global::System.Drawing.Point(4, 163);
			this.RadioButton6.Name = "RadioButton6";
			this.RadioButton6.Size = new global::System.Drawing.Size(55, 20);
			this.RadioButton6.TabIndex = 5;
			this.RadioButton6.Text = "Hour";
			this.RadioButton6.UseVisualStyleBackColor = true;
			this.RadioButton5.AutoSize = true;
			this.RadioButton5.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 10f);
			this.RadioButton5.Location = new global::System.Drawing.Point(6, 132);
			this.RadioButton5.Name = "RadioButton5";
			this.RadioButton5.Size = new global::System.Drawing.Size(51, 21);
			this.RadioButton5.TabIndex = 4;
			this.RadioButton5.Text = "Day";
			this.RadioButton5.UseVisualStyleBackColor = true;
			this.RadioButton4.AutoSize = true;
			this.RadioButton4.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 10f);
			this.RadioButton4.Location = new global::System.Drawing.Point(6, 103);
			this.RadioButton4.Name = "RadioButton4";
			this.RadioButton4.Size = new global::System.Drawing.Size(62, 21);
			this.RadioButton4.TabIndex = 3;
			this.RadioButton4.Text = "Week";
			this.RadioButton4.UseVisualStyleBackColor = true;
			this.RadioButton3.AutoSize = true;
			this.RadioButton3.Checked = true;
			this.RadioButton3.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 10f);
			this.RadioButton3.Location = new global::System.Drawing.Point(6, 75);
			this.RadioButton3.Name = "RadioButton3";
			this.RadioButton3.Size = new global::System.Drawing.Size(65, 21);
			this.RadioButton3.TabIndex = 2;
			this.RadioButton3.TabStop = true;
			this.RadioButton3.Text = "Month";
			this.RadioButton3.UseVisualStyleBackColor = true;
			this.RadioButton2.AutoSize = true;
			this.RadioButton2.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 10f);
			this.RadioButton2.Location = new global::System.Drawing.Point(6, 47);
			this.RadioButton2.Name = "RadioButton2";
			this.RadioButton2.Size = new global::System.Drawing.Size(56, 21);
			this.RadioButton2.TabIndex = 1;
			this.RadioButton2.Text = "Year";
			this.RadioButton2.UseVisualStyleBackColor = true;
			this.RadioButton1.AutoSize = true;
			this.RadioButton1.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 10f);
			this.RadioButton1.Location = new global::System.Drawing.Point(7, 19);
			this.RadioButton1.Name = "RadioButton1";
			this.RadioButton1.Size = new global::System.Drawing.Size(41, 21);
			this.RadioButton1.TabIndex = 0;
			this.RadioButton1.Text = "All";
			this.RadioButton1.UseVisualStyleBackColor = true;
			this.GroupBox1.Controls.Add(this.Label11);
			this.GroupBox1.Controls.Add(this.Label5);
			this.GroupBox1.Controls.Add(this.HideSolution);
			this.GroupBox1.Controls.Add(this.Label13);
			this.GroupBox1.Controls.Add(this.Label8);
			this.GroupBox1.Controls.Add(this.Label3);
			this.GroupBox1.Location = new global::System.Drawing.Point(155, 2);
			this.GroupBox1.Name = "GroupBox1";
			this.GroupBox1.Size = new global::System.Drawing.Size(187, 109);
			this.GroupBox1.TabIndex = 31;
			this.GroupBox1.TabStop = false;
			this.Label11.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 238);
			this.Label11.ForeColor = global::System.Drawing.Color.FromArgb(255, 128, 0);
			this.Label11.Location = new global::System.Drawing.Point(83, 83);
			this.Label11.Name = "Label11";
			this.Label11.Size = new global::System.Drawing.Size(100, 23);
			this.Label11.TabIndex = 46;
			this.Label11.Text = "0";
			this.Label11.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.Label5.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 238);
			this.Label5.ForeColor = global::System.Drawing.Color.Green;
			this.Label5.Location = new global::System.Drawing.Point(83, 36);
			this.Label5.Name = "Label5";
			this.Label5.Size = new global::System.Drawing.Size(100, 23);
			this.Label5.TabIndex = 43;
			this.Label5.Text = "0";
			this.Label5.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.HideSolution.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 238);
			this.HideSolution.Location = new global::System.Drawing.Point(83, 11);
			this.HideSolution.Name = "HideSolution";
			this.HideSolution.Size = new global::System.Drawing.Size(100, 23);
			this.HideSolution.TabIndex = 41;
			this.HideSolution.Text = "0";
			this.HideSolution.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.Label13.AutoSize = true;
			this.Label13.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 11.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 238);
			this.Label13.Location = new global::System.Drawing.Point(8, 85);
			this.Label13.Name = "Label13";
			this.Label13.Size = new global::System.Drawing.Size(58, 18);
			this.Label13.TabIndex = 10;
			this.Label13.Text = "Errors: ";
			this.Label8.AutoSize = true;
			this.Label8.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 11.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 238);
			this.Label8.Location = new global::System.Drawing.Point(8, 38);
			this.Label8.Name = "Label8";
			this.Label8.Size = new global::System.Drawing.Size(56, 18);
			this.Label8.TabIndex = 4;
			this.Label8.Text = "Finded:";
			this.Label3.AutoSize = true;
			this.Label3.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 11.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 238);
			this.Label3.Location = new global::System.Drawing.Point(8, 13);
			this.Label3.Name = "Label3";
			this.Label3.Size = new global::System.Drawing.Size(78, 18);
			this.Label3.TabIndex = 0;
			this.Label3.Text = "Keywords:";
			this.Button4.Location = new global::System.Drawing.Point(348, 87);
			this.Button4.Name = "Button4";
			this.Button4.Size = new global::System.Drawing.Size(152, 23);
			this.Button4.TabIndex = 30;
			this.Button4.Text = "Save";
			this.Button4.UseVisualStyleBackColor = true;
			this.TextBox2.Location = new global::System.Drawing.Point(5, 171);
			this.TextBox2.Multiline = true;
			this.TextBox2.Name = "TextBox2";
			this.TextBox2.ScrollBars = global::System.Windows.Forms.ScrollBars.Vertical;
			this.TextBox2.Size = new global::System.Drawing.Size(312, 183);
			this.TextBox2.TabIndex = 28;
			this.TextBox2.WordWrap = false;
			this.Button2.Location = new global::System.Drawing.Point(348, 36);
			this.Button2.Name = "Button2";
			this.Button2.Size = new global::System.Drawing.Size(152, 23);
			this.Button2.TabIndex = 27;
			this.Button2.Text = "Stop";
			this.Button2.UseVisualStyleBackColor = true;
			this.Button1.Location = new global::System.Drawing.Point(348, 7);
			this.Button1.Name = "Button1";
			this.Button1.Size = new global::System.Drawing.Size(152, 23);
			this.Button1.TabIndex = 26;
			this.Button1.Text = "Start";
			this.Button1.UseVisualStyleBackColor = true;
			this.TextBox1.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 11.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 238);
			this.TextBox1.Location = new global::System.Drawing.Point(5, 8);
			this.TextBox1.Multiline = true;
			this.TextBox1.Name = "TextBox1";
			this.TextBox1.Size = new global::System.Drawing.Size(144, 103);
			this.TextBox1.TabIndex = 25;
			this.TextBox1.Text = "@gmail.com\r\n@aol.com\r\n@hotmail.com\r\n@interia.pl\r\n@ntlworld.com";
			this.TextBox1.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Center;
			this.TabPage2.Controls.Add(this.Button6);
			this.TabPage2.Controls.Add(this.GroupBox4);
			this.TabPage2.Controls.Add(this.Button8);
			this.TabPage2.Controls.Add(this.Button7);
			this.TabPage2.Controls.Add(this.Label7);
			this.TabPage2.Controls.Add(this.ComboBox2);
			this.TabPage2.Controls.Add(this.Label2);
			this.TabPage2.Controls.Add(this.Button5);
			this.TabPage2.Controls.Add(this.Button3);
			this.TabPage2.Controls.Add(this.ComboBox1);
			this.TabPage2.Controls.Add(this.Label1);
			this.TabPage2.Controls.Add(this.NumericUpDown1);
			this.TabPage2.Controls.Add(this.TextBox3);
			this.TabPage2.Location = new global::System.Drawing.Point(4, 22);
			this.TabPage2.Name = "TabPage2";
			this.TabPage2.Padding = new global::System.Windows.Forms.Padding(3);
			this.TabPage2.Size = new global::System.Drawing.Size(505, 359);
			this.TabPage2.TabIndex = 1;
			this.TabPage2.Text = "Get Data";
			this.TabPage2.UseVisualStyleBackColor = true;
			this.Button6.Location = new global::System.Drawing.Point(9, 330);
			this.Button6.Name = "Button6";
			this.Button6.Size = new global::System.Drawing.Size(235, 23);
			this.Button6.TabIndex = 42;
			this.Button6.Text = "Save";
			this.Button6.UseVisualStyleBackColor = true;
			this.GroupBox4.Controls.Add(this.Label19);
			this.GroupBox4.Controls.Add(this.Label20);
			this.GroupBox4.Controls.Add(this.Label9);
			this.GroupBox4.Controls.Add(this.Label10);
			this.GroupBox4.Controls.Add(this.Label12);
			this.GroupBox4.Controls.Add(this.Label14);
			this.GroupBox4.Controls.Add(this.Label15);
			this.GroupBox4.Controls.Add(this.Label16);
			this.GroupBox4.Controls.Add(this.Label17);
			this.GroupBox4.Controls.Add(this.Label18);
			this.GroupBox4.Location = new global::System.Drawing.Point(9, 195);
			this.GroupBox4.Name = "GroupBox4";
			this.GroupBox4.Size = new global::System.Drawing.Size(235, 132);
			this.GroupBox4.TabIndex = 41;
			this.GroupBox4.TabStop = false;
			this.Label19.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 238);
			this.Label19.Location = new global::System.Drawing.Point(131, 77);
			this.Label19.Name = "Label19";
			this.Label19.Size = new global::System.Drawing.Size(100, 23);
			this.Label19.TabIndex = 48;
			this.Label19.Text = "0/0";
			this.Label19.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.Label20.AutoSize = true;
			this.Label20.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 11.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 238);
			this.Label20.Location = new global::System.Drawing.Point(8, 79);
			this.Label20.Name = "Label20";
			this.Label20.Size = new global::System.Drawing.Size(47, 18);
			this.Label20.TabIndex = 47;
			this.Label20.Text = "Used:";
			this.Label9.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 238);
			this.Label9.ForeColor = global::System.Drawing.Color.FromArgb(255, 128, 0);
			this.Label9.Location = new global::System.Drawing.Point(131, 101);
			this.Label9.Name = "Label9";
			this.Label9.Size = new global::System.Drawing.Size(100, 23);
			this.Label9.TabIndex = 46;
			this.Label9.Text = "0";
			this.Label9.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.Label10.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 238);
			this.Label10.ForeColor = global::System.Drawing.Color.Green;
			this.Label10.Location = new global::System.Drawing.Point(131, 56);
			this.Label10.Name = "Label10";
			this.Label10.Size = new global::System.Drawing.Size(100, 23);
			this.Label10.TabIndex = 43;
			this.Label10.Text = "0";
			this.Label10.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.Label12.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 238);
			this.Label12.Location = new global::System.Drawing.Point(131, 33);
			this.Label12.Name = "Label12";
			this.Label12.Size = new global::System.Drawing.Size(100, 23);
			this.Label12.TabIndex = 42;
			this.Label12.Text = "0";
			this.Label12.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.Label14.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 238);
			this.Label14.Location = new global::System.Drawing.Point(131, 11);
			this.Label14.Name = "Label14";
			this.Label14.Size = new global::System.Drawing.Size(100, 23);
			this.Label14.TabIndex = 41;
			this.Label14.Text = "0";
			this.Label14.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.Label15.AutoSize = true;
			this.Label15.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 11.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 238);
			this.Label15.Location = new global::System.Drawing.Point(8, 103);
			this.Label15.Name = "Label15";
			this.Label15.Size = new global::System.Drawing.Size(58, 18);
			this.Label15.TabIndex = 10;
			this.Label15.Text = "Errors: ";
			this.Label16.AutoSize = true;
			this.Label16.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 11.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 238);
			this.Label16.Location = new global::System.Drawing.Point(8, 58);
			this.Label16.Name = "Label16";
			this.Label16.Size = new global::System.Drawing.Size(56, 18);
			this.Label16.TabIndex = 4;
			this.Label16.Text = "Finded:";
			this.Label17.AutoSize = true;
			this.Label17.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 11.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 238);
			this.Label17.Location = new global::System.Drawing.Point(8, 35);
			this.Label17.Name = "Label17";
			this.Label17.Size = new global::System.Drawing.Size(50, 18);
			this.Label17.TabIndex = 2;
			this.Label17.Text = "Proxy:";
			this.Label18.AutoSize = true;
			this.Label18.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 11.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 238);
			this.Label18.Location = new global::System.Drawing.Point(8, 13);
			this.Label18.Name = "Label18";
			this.Label18.Size = new global::System.Drawing.Size(39, 18);
			this.Label18.TabIndex = 0;
			this.Label18.Text = "Urls:";
			this.Button8.Location = new global::System.Drawing.Point(128, 47);
			this.Button8.Name = "Button8";
			this.Button8.Size = new global::System.Drawing.Size(116, 35);
			this.Button8.TabIndex = 40;
			this.Button8.Text = "Stop";
			this.Button8.UseVisualStyleBackColor = true;
			this.Button7.Location = new global::System.Drawing.Point(9, 47);
			this.Button7.Name = "Button7";
			this.Button7.Size = new global::System.Drawing.Size(113, 35);
			this.Button7.TabIndex = 39;
			this.Button7.Text = "Start";
			this.Button7.UseVisualStyleBackColor = true;
			this.Label7.AutoSize = true;
			this.Label7.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 238);
			this.Label7.Location = new global::System.Drawing.Point(87, 146);
			this.Label7.Name = "Label7";
			this.Label7.Size = new global::System.Drawing.Size(59, 16);
			this.Label7.TabIndex = 37;
			this.Label7.Text = "Threads";
			this.ComboBox2.FormattingEnabled = true;
			this.ComboBox2.Items.AddRange(new object[]
			{
				"Email:Pass",
				"User:Pass",
				"Emails",
				"Proxy",
				"Custom"
			});
			this.ComboBox2.Location = new global::System.Drawing.Point(94, 125);
			this.ComboBox2.Name = "ComboBox2";
			this.ComboBox2.Size = new global::System.Drawing.Size(150, 21);
			this.ComboBox2.TabIndex = 36;
			this.ComboBox2.Text = "Email:Pass";
			this.Label2.AutoSize = true;
			this.Label2.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 238);
			this.Label2.Location = new global::System.Drawing.Point(6, 126);
			this.Label2.Name = "Label2";
			this.Label2.Size = new global::System.Drawing.Size(82, 16);
			this.Label2.TabIndex = 35;
			this.Label2.Text = "Results type";
			this.Button5.Location = new global::System.Drawing.Point(128, 6);
			this.Button5.Name = "Button5";
			this.Button5.Size = new global::System.Drawing.Size(116, 35);
			this.Button5.TabIndex = 34;
			this.Button5.Text = "Proxy";
			this.Button5.UseVisualStyleBackColor = true;
			this.Button3.Location = new global::System.Drawing.Point(6, 6);
			this.Button3.Name = "Button3";
			this.Button3.Size = new global::System.Drawing.Size(116, 35);
			this.Button3.TabIndex = 33;
			this.Button3.Text = "Urls";
			this.Button3.UseVisualStyleBackColor = true;
			this.ComboBox1.FormattingEnabled = true;
			this.ComboBox1.Items.AddRange(new object[]
			{
				"No Proxy",
				"Https",
				"Socks4",
				"Socks5"
			});
			this.ComboBox1.Location = new global::System.Drawing.Point(54, 95);
			this.ComboBox1.Name = "ComboBox1";
			this.ComboBox1.Size = new global::System.Drawing.Size(190, 21);
			this.ComboBox1.TabIndex = 32;
			this.ComboBox1.Text = "No Proxy";
			this.Label1.AutoSize = true;
			this.Label1.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 238);
			this.Label1.Location = new global::System.Drawing.Point(6, 97);
			this.Label1.Name = "Label1";
			this.Label1.Size = new global::System.Drawing.Size(42, 16);
			this.Label1.TabIndex = 31;
			this.Label1.Text = "Proxy";
			this.NumericUpDown1.Location = new global::System.Drawing.Point(9, 165);
			global::System.Windows.Forms.NumericUpDown numericUpDown = this.NumericUpDown1;
			int[] array = new int[4];
			array[0] = 1;
			numericUpDown.Minimum = new decimal(array);
			this.NumericUpDown1.Name = "NumericUpDown1";
			this.NumericUpDown1.Size = new global::System.Drawing.Size(235, 20);
			this.NumericUpDown1.TabIndex = 30;
			this.NumericUpDown1.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Center;
			global::System.Windows.Forms.NumericUpDown numericUpDown2 = this.NumericUpDown1;
			int[] array2 = new int[4];
			array2[0] = 50;
			numericUpDown2.Value = new decimal(array2);
			this.TextBox3.Location = new global::System.Drawing.Point(251, 6);
			this.TextBox3.MaxLength = 999999999;
			this.TextBox3.Multiline = true;
			this.TextBox3.Name = "TextBox3";
			this.TextBox3.ReadOnly = true;
			this.TextBox3.ScrollBars = global::System.Windows.Forms.ScrollBars.Vertical;
			this.TextBox3.Size = new global::System.Drawing.Size(249, 347);
			this.TextBox3.TabIndex = 29;
			this.TextBox3.WordWrap = false;
			base.AutoScaleDimensions = new global::System.Drawing.SizeF(6f, 13f);
			base.AutoScaleMode = global::System.Windows.Forms.AutoScaleMode.Font;
			base.ClientSize = new global::System.Drawing.Size(520, 393);
			base.Controls.Add(this.TabControl1);
			base.FormBorderStyle = global::System.Windows.Forms.FormBorderStyle.FixedSingle;
			base.Icon = (global::System.Drawing.Icon)componentResourceManager.GetObject("$this.Icon");
			base.Name = "Form1";
			base.StartPosition = global::System.Windows.Forms.FormStartPosition.CenterScreen;
			this.Text = "Joker Combo Leecher [v1.0]";
			((global::System.ComponentModel.ISupportInitialize)this.BindingSource1).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.VisualStyler1).EndInit();
			this.TabControl1.ResumeLayout(false);
			this.TabPage1.ResumeLayout(false);
			this.TabPage1.PerformLayout();
			this.GroupBox3.ResumeLayout(false);
			this.GroupBox3.PerformLayout();
			this.GroupBox2.ResumeLayout(false);
			this.GroupBox2.PerformLayout();
			this.GroupBox1.ResumeLayout(false);
			this.GroupBox1.PerformLayout();
			this.TabPage2.ResumeLayout(false);
			this.TabPage2.PerformLayout();
			this.GroupBox4.ResumeLayout(false);
			this.GroupBox4.PerformLayout();
			((global::System.ComponentModel.ISupportInitialize)this.NumericUpDown1).EndInit();
			base.ResumeLayout(false);
		}

		// Token: 0x04000018 RID: 24
		private global::System.ComponentModel.IContainer components;
	}
}
